# Generated by Django 4.0 on 2022-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curt_descrition', models.TextField(max_length=255)),
                ('long_descrition', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('cost_marketing', models.FloatField()),
                ('cost_marketing_promotion', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
