# Generated by Django 4.0 on 2022-01-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variações', 'verbose_name_plural': 'Variações'},
        ),
    ]
