# Generated by Django 4.0 on 2022-03-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cost_marketing',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cost_marketing_promotion',
            field=models.FloatField(default=0, verbose_name='Promotion Cost'),
        ),
    ]
